name: zcashname_sdk
description: Dart SDK for the Zcash Name System (ZNS) JSON-RPC API.
version: 0.7.0
repository: https://github.com/zcashme/ZNS
license: MIT

environment:
  sdk: ^3.4.0

dependencies:
  http: ^1.2.0
  cryptography: ^2.7.0
  bech32: ^0.2.2
  meta: ^1.11.0

dev_dependencies:
  test: ^1.25.0
